spring:
  application:
    name: order-service
  datasource:
    url: jdbc:h2:mem:order-db?createDatabaseIfNotExists=true
  cloud:
    stream:
      bindings:
        input-in:
          destination: T1
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092
  h2:
    console:
      enabled: true
server:
  port: 8081
