spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:h2:mem:inventory-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  cloud:
    stream:
      bindings:
        OrderEntityConsumer-in-0:
          destination: T1
          content-type: application/json
      kafka:
        binder:
          brokers: localhost:9092
    function:
      definition: OrderEntityConsumer
  h2:
    console:
      enabled: true
server:
  port: 8082

